spring:
  application:
    name: magazynieruz-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          create_namespaces: true
cors:
  allowed-origins: "https://magazynieruz.vercel.app"
