spring:
  application:
    name: magazynieruz
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres
    username: ${db.username}
    password: ${db.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

security:
  jwt:
    secret-key: ${jwt.secret}
    expiration: ${jwt.expiration}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: false